<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTinx63x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTinx63x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTinx63x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTinx63x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTinx63x\appDevDebugProjectContainer([
    'container.build_hash' => 'Tinx63x',
    'container.build_id' => 'ce232270',
    'container.build_time' => 1658327462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTinx63x');
